import {
    Home,
    User,
    Briefcase,
    CheckSquare,
    Calendar,
    Users,
    BarChart2,
    Settings,
    LogOut,
    Plus,
    Sun,
    Moon,
    Clock,
    Bell,
    Activity,
    FileText,
    List,
    Menu,
  } from "lucide-react"
  
  export const Icons = {
    home: Home,
    user: User,
    briefcase: Briefcase,
    task: CheckSquare,
    calendar: Calendar,
    users: Users,
    chart: BarChart2,
    settings: Settings,
    logout: LogOut,
    plus: Plus,
    sun: Sun,
    moon: Moon,
    clock: Clock,
    bell: Bell,
    activity: Activity,
    file: FileText,
    list: List,
    menu: Menu,
  }
  